version: '3'
services:
  agent:
    build: .
    container_name: agent-pool
    restart: always
    ports:
      - "9091:9091"
    links:
      - redis
    environment:
      DB_CONN: "redis://@redis:6379/0"
  redis:
    image: redis:6
    restart: always
    container_name: agent_redis