version: '3'
services:
  sproxy_pool:
    build: .
    container_name: sproxy_pool
    ports:
      - "9091:9091"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  proxy_redis:
    image: redis:6
    container_name: proxy_redis